version: "3.8"

services:
  db:
    image: postgres:latest
    expose:
      - 5432
    volumes:
      - rtl-db:/var/lib/postgresql/data
    env_file:
      - .env

  core-channels-layer:
    image: redis:latest
    expose:
      - "6379"

  core-asgi:
    build:
      context: .
      dockerfile: Dockerfile.core
    working_dir: /app
    command: "daphne -b 0.0.0.0 -p 80 'rtl.asgi-consumer:application'"
    env_file:
      - .env

    depends_on:
      - core-migration
      - core-channels-layer
      - db

  core-asgi-producer:
    build:
      context: .
      dockerfile: Dockerfile.core
    working_dir: /app
    command: "daphne -b 0.0.0.0 -p 80 'rtl.asgi:application'"
    env_file:
      - .env

    depends_on:
      - core-migration
      - core-channels-layer
      - db

  core-wsgi:
    build:
      context: .
      dockerfile: Dockerfile.core
    working_dir: /app
    command: "gunicorn rtl.wsgi:application -k gevent -b 0.0.0.0:80 --workers=3"
    env_file:
      - .env

    depends_on:
      - core-migration
      - core-channels-layer
      - db

  core-migration:
    build:
      context: .
      dockerfile: Dockerfile.core
    command: python manage.py migrate --noinput
    env_file:
      - .env

    depends_on:
      - db

  core-nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.core.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - core-asgi
      - core-wsgi

    # Tip. Use docker-compose.override.yml to specify ports
    # ports:
    #   - "8000:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - REACT_APP_URL_BACKEND=${REACT_APP_URL_BACKEND}
        - REACT_APP_URL_WS=${REACT_APP_URL_WS}

    volumes:
      - ./conf.d/nginx.app.conf:/etc/nginx/nginx.conf:ro

    # Tip. Use docker-compose.override.yml to specify ports
    # ports:
    #   - "3000:80"

    env_file:
      - .env

volumes:
  rtl-db: