# Generated by Django 4.0.4 on 2022-04-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='remove_on_disconnect',
        ),
    ]
